name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up openjdk-jre
        run: >
         sudo apt-get update &&
         sudo apt-get install --no-install-recommends --yes openjdk-8-jre
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: clojure --help
